- name: Downloading & Installing Essentials
  run: |
    Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
    cmd /c Downloads.bat
